name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  trivy-scan:
    uses: ./.github/workflows/trivy.yml
    with:
      scan-path: "."

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation
    steps:
      - uses: actions/checkout@v4
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          bb: 'latest'
      - name: Run Tests
        run: bb test
      - name: Run Lint
        run: bb lint
      - name: Run Audit
        run: bb audit-vulns-clj
      - name: Docker Build
        run: bb docker-build